controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_cart_add:
    path: '/cart/add/{id}'
    controller: 'App\Controller\CartController::add'
    methods: ['GET']
   
app_cart_index:
    path: '/cart'
    controller: 'App\Controller\CartController::index'
    methods: ['GET']
